#!/usr/bin/python

#
# Converts standard input lines to their respective column counts
#
#

import os,sys

delimiter = sys.argv[1]

line = sys.stdin.readline()
while line:
	line = line[:-1]
	l = line.split(delimiter)
	print len(l)	
	line = sys.stdin.readline()
