#!/usr/bin/env python
 
"""
 Author: Saophalkun Ponlu (http://phalkunz.com)
 Contact: phalkunz@gmail.com
 Date: May 23, 2009
 Modified: June 15, 2009
 
 Additional modifications:
 Author: Phil Christensen (http://bubblehouse.org)
 Contact: phil@bubblehouse.org
 Date: February 22, 2010
"""
 
import os, sys, re, subprocess
 
tabsize = 4
 
colorizedSubcommands = (
	'status',
	'st',
	'add',
	'remove',
	'diff',
	'update',
	'up',
)
 
color = {
	"black"	:	"30",
	"red"	:	"31",
	"green"	:	"32",
	"brown"	:	"33",
	"blue"	:	"34",
	"violet"	:	"35",
	"cyan"	:	"36",
	"gray"	:	"37",
	"darkGray"	: "1;30",
	"lightBlue"	:	"1;34",
	"yellow" : "1;33",
	"lightRed"	:	"1;31",
}

effects = {
	"bold" : "1",
}

def on (c):
	return ";"+str(10+int(color[c]));

statusColors = {
    "M"     : color["brown"],
    "U"     : "31",     
    "R"		: color["blue"],
    "G"		: color["black"]+on("red"),
    "\?"    : color["lightRed"],     # grey,
    "\!"    : color["red"],
    "A"     : color["green"], 
    "X"     : color["red"], 
    "C"     : color["black"]+on("cyan"),
    "-"     : color["red"], 
    "D"     : color["yellow"], 
    "\+"    : "32",     # green
}
 
def colorize(line): 
    for color in statusColors:
        if re.match(color, line):
            return ''.join(("\033[", statusColors[color], "m", line, "\033[m"))
    else:
        return line
 
def escape(s):
    s = s.replace('$', r'\$')
    s = s.replace('"', r'\"')
    s = s.replace('`', r'\`')
    return s
 
passthru = lambda x: x
quoted = lambda x: '"%s"' % escape(x)
 
if __name__ == "__main__":

    cmd = ' '.join(['svn']+[(passthru, quoted)[' ' in arg](arg) for arg in sys.argv[1:]])
    output = subprocess.Popen(cmd, shell=True, stdout=subprocess.PIPE)
    cancelled = False
    for line in output.stdout:
        line = line.expandtabs(tabsize)
        if(sys.argv[1] in colorizedSubcommands):
            line = colorize(line)
        try:
            sys.stdout.write(line)
        except:
            sys.exit(1)
