#!/usr/bin/python

import os,sys
import zookeeper
import time
from optparse import OptionParser
from zkutils import *

parser = OptionParser()
parser.add_option("-s","--server",dest="server",default='localhost:2181',
                help="zookeeper server list h:p,h:p,h:p")

zookeeper.set_debug_level(zookeeper.LOG_LEVEL_ERROR)

(options,args) = parser.parse_args()

if len(args) != 1:
    parser.print_help()
    sys.exit(1)

initialize(options.server)

try:
	for node_name in find(args[0]):
		print node_name
except KeyboardInterrupt,e:
	pass
