#!/usr/bin/python

import os,sys
import zookeeper
import time
from optparse import OptionParser
from zkutils import *
import pprint

parser = OptionParser()
parser.add_option("-s","--server",dest="server",default='localhost:2181',
                help="zookeeper server list h:p,h:p,h:p")

zookeeper.set_debug_level(zookeeper.LOG_LEVEL_ERROR)

(options,args) = parser.parse_args()

if len(args) == 0:
    parser.print_help()
    sys.exit(1)

initialize(options.server)

node_names = args

for node_name in node_names:
	n = get_node(node_name)
	pprint.pprint(n)
